apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiaowang
spec:
  selector:
    matchLabels:
      controller: xiaowang
  template:
    metadata:
      labels:
        controller: xiaowang
    spec:
      containers:
      - args: 
        - -kubeconfig=/tmp/kubeconfig
        - -master=https://kubernetes.default.svc:443
        - -name=小王
        image: github.com/trainyao/playground/crd-controller/handmade:latest
        imagePullPolicy: IfNotPresent
        name: controller
        volumeMounts:
        - mountPath: /tmp/kubeconfig
          name: kubeconfig
          readOnly: true
      volumes:
      - hostPath:
          path: /home/trainyao/.kube/config
        name: kubeconfig
