apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiaoming
spec:
  selector:
    matchLabels:
      controller: xiaoming
  template:
    metadata:
      labels:
        controller: xiaoming
    spec:
      containers:
      - args: 
        - -name=小明
        image: github.com/trainyao/playground/crd-controller/kb:latest
        imagePullPolicy: IfNotPresent
        name: controller
        env:
        - name: KUBECONFIG
          value: /tmp/kubeconfig
        volumeMounts:
        - mountPath: /tmp/kubeconfig
          name: kubeconfig
          readOnly: true
      volumes:
      - hostPath:
          path: /home/trainyao/.kube/config
        name: kubeconfig
