apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiaoming
spec:
  selector:
    matchLabels:
      controller: xiaoming
  template:
    metadata:
      labels:
        controller: xiaoming
    spec:
      containers:
      - args: 
        # ["-c", "/usr/bin/controller -kubeconfig=/tmp/kubeconfig -master=https://kubernetes.default.svc:443 -name=小明"]
        #command: ["/bin/rh"]
        - -kubeconfig=/tmp/kubeconfig
        - -master=https://kubernetes.default.svc:443
        - -name=小明
        image: github.com/trainyao/playground/crd-controller/handmade:latest
        imagePullPolicy: IfNotPresent
        name: controller
        volumeMounts:
        - mountPath: /tmp/kubeconfig
          name: kubeconfig
          readOnly: true
      volumes:
      - hostPath:
          path: /home/trainyao/.kube/config
        name: kubeconfig
