apiVersion: handmade.crd.playground.trainyao.io/v1
kind: GoddessMoment
metadata:
  name: wantfood
spec:
  foodDemand:
  - name: 珍珠奶茶
status:
  foodDemand:
  - name: 珍珠奶茶
    status: Pending
    claimBy: ""
    claimTime: "1970-01-01T00:00:00Z"
    arrivalTime: "1970-01-01T00:00:00Z"
